services:
  api:
    container_name: outscout-server
    image: khizer30/outscout-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "9464:9464"
    env_file:
      - apps/api/.env
    restart: unless-stopped

  worker:
    container_name: outscout-worker
    image: khizer30/outscout-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "dist/src/worker.js"]
    env_file:
      - apps/api/.env
    restart: unless-stopped

  node-exporter:
    container_name: outscout-node-exporter
    image: prom/node-exporter:latest
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/host/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "9100:9100"
    restart: unless-stopped

  prometheus:
    container_name: outscout-prometheus
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.config.file=/etc/prometheus/web.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheusWeb.yml:/etc/prometheus/web.yml
      - prometheus_data:/prometheus
    restart: unless-stopped

volumes:
  prometheus_data:
