export type AuditAction =
  | "USER_CREATED"
  | "USER_UPDATED"
  | "USER_DELETED"
  | "COMPANY_CREATED"
  | "COMPANY_UPDATED"
  | "COMPANY_DELETED"
  | "EMAIL_SETTINGS_UPDATED"
  | "RULE_CREATED"
  | "RULE_UPDATED"
  | "RULE_DELETED";
